### ISSUE TITLE
Apply plugins to certain stores 

### ISSUE THREAD

**Issue by silverberrylog** [posva/pinia#1128]
### What problem is this solving

I'd like to apply plugins to certain stores only. 

### Proposed solution

The 'defineStore' function should provide a 'plugins' option where you include the wanted plugins. This would look similar to vuex's plugins option:

```js
import { createStore } from 'vuex'
import plugin from './plugin'

const store = createStore({
    // ...  
    plugins: [plugin]
})
```

### Describe alternatives you've considered

This is what I'm currently using:
```js
// store definition
export default defineStore('storeName', {
    // ...
    plugins: {
        pluginName: true
    },
})
```
```js
// plugin definition
export default function pluginName({ options }) {
    if (!options.plugins.pluginName) return
    // ...
}
```

**Comment by posva** [comment]
Right now, this can be implemented in a very straightforward plugin. You could have different APIs like registering plugins with names and then applying them by their name in store options

```js
const piniaPlugins = createPiniaPluginManager()
piniaPlugins.add('pluginName', plugin)

pinia.use(piniaPlugins)
// can also add them later on
piniaPlugins.add('another one', plugin2)
```

in a store def:

```js
defineStore('id', {
  // ...
  plugins: ['pluginName']
})
```

I don't think this should exist out of the box because it's simple to create as an external package and there are other ways of implementing this. For instance, plugins could also add a custom option `isPluginXDisabled` that defaults to false/true, and allow stores to enable/disable the plugin
