### ISSUE TITLE
$subscribe handler invoked twice for single $patch operation

### ISSUE THREAD

**Issue by mykwillis** [posva/pinia#1129]
### Reproduction
I've created a failing test case in the pinia repository here:

https://github.com/mykwillis/pinia/commit/07d91c0c6ebf095eb4de3ec4476059cd94571e91

```js
    it('triggers subscribe only once on $patch', async () => {
      const s1 = useStore()
      const spy1 = jest.fn()

      s1.$subscribe(spy1)

      // First mutation: works as expected
      s1.$patch({ user: 'Edu' })
      await Promise.resolve()
      expect(spy1).toHaveBeenCalledTimes(1)
      expect(spy1).not.toHaveBeenCalledWith(
        expect.objectContaining({
          storeId: 'main',
          type: MutationType.direct,
        }),
        s1.$state
      )

      //
      // Second mutation: for some reason we get two $subscribe notifications:
      // one with MutationType.patch, and one with MutationType.direct
      //
      // If we replace both instances of `await Promise.resolve()` (the one above
      // and the one that follows) with `await nextTick()`, it works as expected???
      //
      s1.$patch({ user: 'Myk' })
      await Promise.resolve()

      // fails
      expect(spy1).not.toHaveBeenCalledWith(
        expect.objectContaining({
          storeId: 'main',
          type: MutationType.direct,
        }),
        s1.$state
      )

      // fails
      expect(spy1).toHaveBeenCalledTimes(2)
    })
```
### Steps to reproduce the behavior

In [the submitted branch](https://github.com/mykwillis/pinia/tree/multiple-subscribe-notifications), run `npm run test`.

1. Create a subscription to a store with $subscribe
2. Invoke store.$patch() with updated properties
3. Perform an async operation
4. Invoke store.$patch() with updated properties
5. Perform an async operation

### Expected behavior

The subscription handler given to `store.$subscribe()` should be invoked exactly one time for each call to `store.$patch()`. Each invocation should have a mutation.type of `MutationType.patch`.

### Actual behavior

The subscription handler is invoked once for the first `store.$patch()`, but it is invoked TWICE for the second `store.$patch()`. For the second call to `$patch()` we see BOTH a MutationType.patch AND a MutationType.direct.

### Additional information

I boiled this down from a more complicated situation in my actual project. Strangely, if I change the stand-in async operations to use `await nextTick()` instead of `await Promise.resolve()`, then I don't see the problem. I have no idea why this would be.

**Comment by posva** [comment]
I added a failing test in 9b7a472 and I cannot pinpoint where this comes from... Anything other than an "empty" useless await (e.g. `await null`) works which is really weird... As a workaround, you can remove the `await` or await one tick. Any help on this is welcome.

**Comment by lazzzis** [comment]
I happen to encounter this bug too. My code looks like this:
```js
store.$subscribe((mutation) => {
  console.log(mutation.type)
})

async function test() {
  store.$patch({ count: 2 })
  await Promise.resolve()
  store.$patch({ count: 20 })
}

test()
```

It seems we didn't reset the [`isListening`](https://github.com/vuejs/pinia/blob/0d65f9e1a0f07569cf9f70b16834353aea72ba81/packages/pinia/src/store.ts#L263) in `createSetupStore` of `store.ts` correctly.
The flow looks like this:
1. store.$patch({count: 2}): isListening is set `false`
2. update store and execute `nextTick().then(() => { isListening = true })`
3. `triggerSubscriptions` is called to dispatch events to listeners
4. callback of `watch` in the implementation of [`$subscribe`](https://github.com/vuejs/pinia/blob/0d65f9e1a0f07569cf9f70b16834353aea72ba81/packages/pinia/src/store.ts#L392) is triggered. But since `isListening` is false, it is skipped.
5. store.$patch({count: 20}) is called and isListening is set `false`. Note that `isListening` is not reset to true.
6. update store and execute `nextTick().then(() => { isListening = true })`
7. `triggerSubscriptions` is called to dispatch events to listeners
8. **Somehow callback in step 2 is executed now and `isListening` is set true.**
9. callback of `watch` in the implementation of [`$subscribe`](https://github.com/vuejs/pinia/blob/0d65f9e1a0f07569cf9f70b16834353aea72ba81/packages/pinia/src/store.ts#L392) is triggered. Note that `isListening` is true now and so a `mutation.direct` is mistakenly dispatched to all listeners.

I tried to fix that. Mutating `isListening` by temporarily watching the store works in my case:
```js
    let stopWatcher: WatchStopHandle | null
    let remove = () => {
      if (stopWatcher != null) stopWatcher()
    }
    stopWatcher = scope.run(() =>
      watch(
        pinia.state.value[$id],
        () => {
          isListening = true
          remove()
        },
        {}
      )
    )!

    if (typeof partialStateOrMutator === 'function') { /**...*/ }
    else { /**...*/ }

    // nextTick().then(() => {
    //   isListening = true
    // })
```

I guess this is somehow related to how Vue manages its internal event queue. But I am not familiar with that and not sure if my proposal is 100% correct.

**Comment by posva** [comment]
Thanks a lot for the dive! This was really helpful to fix it by using a symbol to keep track of the last active listener.
