### ISSUE TITLE
watcher does not fire when readonly is used in parent object

### ISSUE THREAD

**Issue by kouts** [posva/pinia#1175]
### Reproduction

https://codesandbox.io/s/pinia-readonly-f3jzwm?file=/src/components/Users.vue

### Steps to reproduce the bug

- Visit the CodeSandbox example [here](https://codesandbox.io/s/pinia-readonly-f3jzwm?file=/src/components/Users.vue). You'll be presented with a list of users that comes from an API.
This list of users is wrapped with a `readonly` and fed to the template.
- Click on a user, this updates the store with the selected user.
There is a watcher attached to the `user` object inside the [store](https://codesandbox.io/s/pinia-readonly-f3jzwm?file=/src/store.js), you'll notice that this watcher does not fire although the data seems to update ok.

### Expected behavior

The expected behavior should be that the watcher should fire when the `user` object changes inside the store as it fires when the `users` list is not wrapped with `readonly`.
In order to see the expected behavior you can comment line 31 and uncomment line 34 in the [Users.vue](https://codesandbox.io/s/pinia-readonly-f3jzwm?file=/src/components/Users.vue) file.
You'll notice that everytime a user is selected, the watcher fires as expected (there's a console log with the user info).

### Actual behavior

When a property of a `readonly` object is referenced as data inside a Pinia store, a watcher attached to that data is not firing when the data changes.

**Comment by posva** [comment]
This seems to happen without pinia too [SFC Playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgd2F0Y2gsIHJlYWRvbmx5LCBvbk1vdW50ZWQsIHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuICBcbiAgY29uc3QgdXNlciA9IHJlZih7IGlkOiAwLCBuYW1lOiBcIlwiIH0pO1xuXG4gIC8vIHVzZVN0b3JhZ2UgZG9lc24ndCB3b3JrIGVpdGhlciB3aGVuIGRhdGEgaXMgZmV0Y2hlZCB1c2luZyB1c2VRdWVyeVxuICAvLyBjb25zdCB1c2VyID0gdXNlU3RvcmFnZSgndXNlcicsIHsgaWQ6IDAsIG5hbWU6ICcnIH0pXG5cblxuICAvLyBUaGlzIHdhdGNoZXIgZG9lc24ndCBmaXJlIHdoZW4gZGF0YSBpcyBmZXRjaGVkIHVzaW5nIHVzZVF1ZXJ5XG4gIHdhdGNoKHVzZXIsIChuVikgPT4ge1xuICAgIGNvbnNvbGUubG9nKFwid2F0Y2hlciBmaXJlZFwiKTtcbiAgICBjb25zb2xlLmxvZyhuViwgdXNlci52YWx1ZSk7XG4gIH0pO1xuICBcbiAgY29uc3Qgc3RvcmUgPSByZWFjdGl2ZSh7IHVzZXIgfSlcbiAgXG4gIGNvbnN0IGRhdGEgPSByZWYoW1xue1xuaWQ6IDEsXG5lbWFpbDogXCJnZW9yZ2UuYmx1dGhAcmVxcmVzLmluXCIsXG5maXJzdF9uYW1lOiBcIkdlb3JnZVwiLFxubGFzdF9uYW1lOiBcIkJsdXRoXCIsXG5hdmF0YXI6IFwiaHR0cHM6Ly9yZXFyZXMuaW4vaW1nL2ZhY2VzLzEtaW1hZ2UuanBnXCJcbn0sXG57XG5pZDogMixcbmVtYWlsOiBcImphbmV0LndlYXZlckByZXFyZXMuaW5cIixcbmZpcnN0X25hbWU6IFwiSmFuZXRcIixcbmxhc3RfbmFtZTogXCJXZWF2ZXJcIixcbmF2YXRhcjogXCJodHRwczovL3JlcXJlcy5pbi9pbWcvZmFjZXMvMi1pbWFnZS5qcGdcIlxufV0pO1xuXG4gICAgLy8gV2F0Y2hlciBpcyBhcHAgc3RvcmUgZG9lcyBub3QgZmlyZSB3aGVuIHJlYWRvbmx5IGlzIHdyYXBwZWQgYXJvdW5kIGRhdGFcbiAgICBjb25zdCB1c2VycyA9IHJlYWRvbmx5KGRhdGEpO1xuICBcbiAgZnVuY3Rpb24gY2hhbmdlKCkge1xuICAgIC8vIHVzZXIudmFsdWUgPSB1c2Vycy52YWx1ZVswXVxuICAgIHN0b3JlLnVzZXIgPSB1c2Vycy52YWx1ZVswXVxuICB9XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxidXR0b24gQGNsaWNrPVwic3RvcmUudXNlciA9IHVzZXJzWzFdXCI+XG4gICAgQ2xpY2sgbWVcbiAgPC9idXR0b24+XG4gIDxidXR0b24gQGNsaWNrPVwiY2hhbmdlKClcIj5cbiAgICBDaGFuZ2UgZnJvbSBzY3JpcHRcbiAgPC9idXR0b24+XG4gIDxwcmU+e3sgc3RvcmUudXNlciB9fTwvcHJlPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=).
I don't think this is a Vue bug though because watching a readonly source is pointless (as it cannot be written) and therefor leaves the watcher unusable. I think you likely need to create a copy of the readonly user or use `toRaw()` [like this](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgd2F0Y2gsIHJlYWRvbmx5LCBvbk1vdW50ZWQsIHJlYWN0aXZlLCB0b1JhdyB9IGZyb20gJ3Z1ZSdcbiAgXG4gIGNvbnN0IHVzZXIgPSByZWYoeyBpZDogMCwgbmFtZTogXCJcIiB9KTtcblxuICAvLyB1c2VTdG9yYWdlIGRvZXNuJ3Qgd29yayBlaXRoZXIgd2hlbiBkYXRhIGlzIGZldGNoZWQgdXNpbmcgdXNlUXVlcnlcbiAgLy8gY29uc3QgdXNlciA9IHVzZVN0b3JhZ2UoJ3VzZXInLCB7IGlkOiAwLCBuYW1lOiAnJyB9KVxuXG5cbiAgLy8gVGhpcyB3YXRjaGVyIGRvZXNuJ3QgZmlyZSB3aGVuIGRhdGEgaXMgZmV0Y2hlZCB1c2luZyB1c2VRdWVyeVxuICB3YXRjaCh1c2VyLCAoblYpID0+IHtcbiAgICBjb25zb2xlLmxvZyhcIndhdGNoZXIgZmlyZWRcIik7XG4gICAgY29uc29sZS5sb2coblYsIHVzZXIudmFsdWUpO1xuICB9KTtcbiAgXG4gIGNvbnN0IHN0b3JlID0gcmVhY3RpdmUoeyB1c2VyIH0pXG4gIFxuICBjb25zdCBkYXRhID0gcmVmKFtcbntcbmlkOiAxLFxuZW1haWw6IFwiZ2VvcmdlLmJsdXRoQHJlcXJlcy5pblwiLFxuZmlyc3RfbmFtZTogXCJHZW9yZ2VcIixcbmxhc3RfbmFtZTogXCJCbHV0aFwiLFxuYXZhdGFyOiBcImh0dHBzOi8vcmVxcmVzLmluL2ltZy9mYWNlcy8xLWltYWdlLmpwZ1wiXG59LFxue1xuaWQ6IDIsXG5lbWFpbDogXCJqYW5ldC53ZWF2ZXJAcmVxcmVzLmluXCIsXG5maXJzdF9uYW1lOiBcIkphbmV0XCIsXG5sYXN0X25hbWU6IFwiV2VhdmVyXCIsXG5hdmF0YXI6IFwiaHR0cHM6Ly9yZXFyZXMuaW4vaW1nL2ZhY2VzLzItaW1hZ2UuanBnXCJcbn1dKTtcblxuICAgIC8vIFdhdGNoZXIgaXMgYXBwIHN0b3JlIGRvZXMgbm90IGZpcmUgd2hlbiByZWFkb25seSBpcyB3cmFwcGVkIGFyb3VuZCBkYXRhXG4gICAgY29uc3QgdXNlcnMgPSByZWFkb25seShkYXRhKTtcbiAgXG4gIGZ1bmN0aW9uIGNoYW5nZSgpIHtcbiAgICAvLyB1c2VyLnZhbHVlID0gdXNlcnMudmFsdWVbMF1cbiAgICBzdG9yZS51c2VyID0gdG9SYXcodXNlcnMpLnZhbHVlWzBdXG4gIH1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGJ1dHRvbiBAY2xpY2s9XCJzdG9yZS51c2VyID0gdG9SYXcodXNlcnMpWzFdXCI+XG4gICAgQ2xpY2sgbWVcbiAgPC9idXR0b24+XG4gIDxidXR0b24gQGNsaWNrPVwiY2hhbmdlKClcIj5cbiAgICBDaGFuZ2UgZnJvbSBzY3JpcHRcbiAgPC9idXR0b24+XG4gIDxwcmU+e3sgc3RvcmUudXNlciB9fTwvcHJlPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=) to get a raw copy that can be made reactive.
