### ISSUE TITLE
Nuxt3 + Plugin + useAsyncData - Augmenting store leads to weird behaviour

### ISSUE THREAD

**Issue by mgiraud** [posva/pinia#1272]
### Reproduction

https://github.com/mgiraud/nuxt3-pinia-issue

### Steps to reproduce the bug

* yarn dev
* open navigator and check the values

The code is very simple, maybe i'm misusing pinia but this behaviour is weird 

### Expected behavior

You should read `should see this|default`

### Actual behavior

we  read `default|default`

### Additional information

* There's a mismatch between the client and the server
* The `test` state variable acts like it's shared between stores on server side

**Comment by posva** [comment]
Your stores are empty. Did you forget to push something?

**Comment by mgiraud** [comment]
The store contains the var 'test' and the function `setData` defined in the pinia plugin

**Comment by posva** [comment]
Ah, I see. Note that you are not setting the state, which could be intentional, but in this case, you are using it in async data which means it needs to be serialized later, so you probably want to put it in `$state` too:

```ts
function piniaExtendPlugin({ store }: PiniaPluginContext) {
  const value = ref('default')
  store.$state.test = value
  store.test = toRef(store.$state, 'test')
  return {
    setData: (data) => {
      store.$state.test = data
    },
  }
}
```

https://pinia.vuejs.org/core-concepts/plugins.html#adding-new-state

That way the state is serialized. **But this is not going to work either** because plugins get applied after state hydration meaning that your plugin will override the state that was set during SSR when creating the store on client side. You could avoid this by doing checking if the state exists:

```ts
function piniaExtendPlugin({ store }: PiniaPluginContext) {
  // or Object.hasOwn(store.$state, 'test') in modern browsers
  if (!Object.prototype.hasOwnProperty.call(store.$state, 'test')) {
    const value = ref('default')
    store.$state.test = value
  }
  // always set the direct access (necessary for setup stores)
  store.test = toRef(store.$state, 'test')

  return {
    setData: (data) => {
      store.$state.test = data
    },
  }
}
```

This **should** work but will currently fails because stores without a `state` option are considered as setup stores and treated the wrong way, which is a bug. So, as a workaround add an empty state to your stores `state: () => ({})`.

The docs will be updated to make the example clearer but this made me wonder if plugins should receive the initialState (counts as a check of server-rendered and avoid breaking reactivity) to make this simpler.
Also, should there be a way to make plugins run before hydration? I don't think so because it would create other problems if you try to use the state in the plugin.
