### ISSUE TITLE
Pinia state undefined in vue dev tools

### ISSUE THREAD

**Issue by SoetZombie** [posva/pinia#1358]
### Reproduction

Yes

### Steps to reproduce the bug

Defined store with following:

```
import { defineStore } from 'pinia';

export const useUsersStore = defineStore({
  id: 'user',
  state: (): UserState => ({
    user: {} as User,
  }),
  getters: {
    token: (state) => state.user.token,
  },
  actions: {
    async addUserToken(token: string | null) {
      this.user = { token: token };
    },
  },
});
```

Access the store in component

```
const usersStore = useUsersStore();
const { user } = storeToRefs(usersStore);
```

Open dev tools

### Expected behavior

I expect the store state to be visible in the dev tools.

### Actual behavior

![image](https://user-images.githubusercontent.com/23699014/173035758-4616b27e-a23a-467f-b62f-6b44008b104d.png)

The _custom object contains the values, however it doesn't look like it works as expected.

**Comment by borisrose** [comment]
Have you found a solution to it ?

**Comment by MichaelHeydon** [comment]
I believe I'm also encountering this issue

**Comment by alecStewart1** [comment]
I'm having this issue as well. The single value in a store is an array of objects that has actual data inside of it, but it comes back as undefined.

**Comment by patricioalex** [comment]
Eu tive o mesmo problema.

Porém, o que percebi foi que o setup mostra a variavel de estado undefined.

![image](https://user-images.githubusercontent.com/46056058/178061608-641c28b3-c2c0-434f-b143-3cc8d27339be.png)



Mas logo abaixo, geralmente os ultimos do dev tools, mostra o arquivo do estado com so dados definidos.
Acessando a variavel você consegue pegar os dados que definiu no inicio ou depois de atribuir algo a ele.
![image](https://user-images.githubusercontent.com/46056058/178061727-3f0162e1-3fe5-4f6a-8c14-088478b37990.png)

**Comment by eminos** [comment]
I'm having this same issue and I can't figure out why. It used to work. I don't know what I did to break it :)

**Comment by CreativeWarlock** [comment]
On a side note, the property of a state also becomes undefined when you
a) use a getter method has the same name as one of the props defined in the state,
b) use async modifier at the state definition, like so:
`async state: () => {
   let userId = await axios.get('urlToMyFancyUserService')
   return {
      id: userId
   }
},`

**Comment by arefashrafi** [comment]
This was the issue for me

**Comment by bartduisters** [comment]
I have this same issue. However, I noticed that the `undefined` occurs while watching the store through the `component scope` in Vue Devtools.
<img width="768" alt="Screenshot 2022-07-20 at 20 04 45" src="https://user-images.githubusercontent.com/43420049/180052248-8a861fd2-1e24-41f1-b492-761132459d68.png">

When looking at the same store/state from the `Pinia scope`, it does look as expected.
<img width="733" alt="Screenshot 2022-07-20 at 20 04 22" src="https://user-images.githubusercontent.com/43420049/180052514-61e915b0-e4d4-4639-892b-c8541d2df7a3.png">

This occurs in both a plain new Vue project and in Quasar projects.

# Bug information

**Steps to reproduce**
- `npm init vite`
- Pick `no` for each option, except for Pinia
- In `App.vue` add the following code to the `script` part:
```js
import { useCounterStore } from "./stores/counter";
const store = useCounterStore();
console.log(store.counter);
```
- Visit `Vue Devtools`, click on `Components`, click on `<App />`

**Expected**
The Pinia state to reflect the state object as seen in the `Pinia` tab.

<img width="862" alt="Screenshot 2022-07-20 at 20 17 42" src="https://user-images.githubusercontent.com/43420049/180053987-a97524c3-8e65-4c70-b8fb-1d811d9f1134.png">


**Actual**
The Pinia state shows `undefined`, it has a `_custom` property, which holds a `value` property, which contains the actual state.

<img width="1137" alt="Screenshot 2022-07-20 at 20 17 03" src="https://user-images.githubusercontent.com/43420049/180054057-3793f27c-b6b1-4247-91fa-fffbbc8cf141.png">

**Workaround**
Investigate your store from within the `Pinia tab`, instead of the `Component tab`.

**Comment by marr** [comment]
Seeing this issue as well. One observation is that the `_isOptionsAPI` value is _true_, even though I'm using the `script setup` composition api.

Also, the Pinia inspector displays the correct state values.

**Comment by bartduisters** [comment]
@posva The reproduction is posted in my previous comment. Is it sufficient?
