### ISSUE TITLE
Augmenting a store via Nuxt3 plugin fails without error, when using a store value. After that all other plugins also fail

### ISSUE THREAD

**Issue by henk23** [posva/pinia#1841]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-ugwqhe?file=app.vue

### Steps to reproduce the bug

When trying to add a pinia plugin inside a Nuxt3 plugin like `nuxtApp.$pinia.use()`, while using a value from a store, this plugin will not work. After this, all other plugins will also fail. See in the repro: plugin 00 and plugin 02 have the exact same code, but 00 works and 02 does not, because 01 looks like this:

    // plugins/myPlugin.js
    import { useMainStore } from '~/stores/main';
    
    export default defineNuxtPlugin((nuxtApp) => {
      const mainStore = useMainStore();
    
      nuxtApp.$pinia.use(() => ({
        notWorkingPluginValue: 'this does not work: ' + mainStore.myValue,
      }));
    });

### Expected behavior

All three pinia plugins work, augmenting the store with their respective values.
OR: Seeing an error message: "Sorry, you cannot use a store value inside a plugin for reason XY"

### Actual behavior

Only the first plugin works. The second and third do not add any properties to the store. No errors.

**Comment by posva** [comment]
I added a note to the docs but this is expected behavior as the plugin is invoked when the store is created so **plugins must be added before creating the stores** (calling `useStore()` for the first time). In your case, the store is created before adding the 2nd plugin to pinia so all pinia plugins coming after that one (including the 2nd) have no effect on that specific store but will affect any other plugin created after that store.

Also note this is unrelated to nuxt
