### ISSUE TITLE
Pinia does not work well with iframes

### ISSUE THREAD

**Issue by felipemarcos** [posva/pinia#1915]
### Reproduction

https://codesandbox.io/s/vue3-pinia-iframe-cre5st?file=/components/App.vue

### Steps to reproduce the bug

1. Have an app that shows an iframe
2. Inside the iframe, create a new vue instance as a separate entry.
3. Pass a pinia instance from the main vue down to the iframe instance.
4. Open the browser console, and you will see the error below: 

<img width="882" alt="Screenshot 2023-01-04 at 00 07 58" src="https://user-images.githubusercontent.com/3706755/210476970-68e0386a-af59-4552-b43f-733fc269d886.png">

For some reason, pinia fails to set the current active pinia instance if it was not created in the same document.

We need to manually call `setActivePinia(piniaInstance)` to eliminate this error, but it reveals other problems:

1. The iframe instance will not re-render when the state changes. 
2. Stores lose reactivity when passed down to iframes.
3. Actions work, but they mutate the main pinia instance only.

### Expected behavior

Sharing a pini instance from one document to another in a same-domain iframe should maintain reactivity.

### Actual behavior

Stores lose reactivity when passing a pinia instance to an iframe.

### Additional information

**app 1**

```js
window.__piniaInstance = createPinia()
createApp(App)
  .use(window.__piniaInstance)
  .mount("#app");
```

**app 2 (iframe)**
```js
createApp(Subapp)
  .use(window.parent.__piniaInstance) // We access the parent window object to get the pinia instance.
  .mount("#subapp");
```

**Comment by posva** [comment]
This happens because you end up having two versions of Vue and they cannot see each other changes. It's not related to pinia itself, it's how the reactivity works in Vue. In fact, if you use a `ref()` or `reactive()` instead of a pinia store, you will face the exact same issue (I tested locally but couldn't put it on the codesandbox because of permission issues).

In order to share reactive variables between iframes, you will need to go a bit further. I couldn't find an existing plugin for Vue to connect two Vue apps in different iframes, but it should be doable so if you end up building the plugin, please post it back here to share with others!

**Comment by felipemarcos** [comment]
> In order to share reactive variables between iframes, you will need to go a bit further.

Could you give me some direction or a StackOverflow discussion?
I tried searching for this, but I couldn't find anything. I will definitely build a plugin if I know what to look for. Thanks!

**Comment by posva** [comment]
I wish I could but I don't have more information. Good luck!

**Comment by MattStellisoft** [comment]
Hi @felipemarcos, did you find/ develop a solution for this problem? If not I'm going to have to write a library to take care of it as it's something I really need.
