### ISSUE TITLE
`typescript 5.0.0-beta` conflicts with configuration of this plugin:`package. json`->`peerDependencies` ->`typescript: >=4.4.4`, resulting in installation failure

### ISSUE THREAD

**Issue by mxp131011** [posva/pinia#1970]
### Reproduction

`typescript 5.0.0-beta` conflicts with configuration of this plugin:`package. json`->`peerDependencies` ->`typescript: >=4.4.4`, resulting in installation failure

### Steps to reproduce the bug

1. package.json set "typescript": "5.0.0-beta"
2. delete and node_modulespackage-lock.json
3. run npm install

 ![image](https://user-images.githubusercontent.com/31055355/215922772-a9301548-1235-49f9-9645-078d5206ad39.png)

### Expected behavior

installed successfully

### Actual behavior

installation failed

**Comment by mxp131011** [comment]
temporary solution : `npm install --force`

**Comment by posva** [comment]
This is expected as beta (and other non-stable) versions are not officially supported and that's why semver doesn't cover it. You have to configure the package manager to allow them if you want but there is no guarantee they will work.

Note this is not exactly related to pinia, it's more of a semver convention and a package manager question.
