### ISSUE TITLE
pinia state with computed has bug, the computed reactive not trigger sometimes.

### ISSUE THREAD

**Issue by WormGirl** [posva/pinia#2265]
### Reproduction

https://github.com/WormGirl/pinia_bug_reproduction

### Steps to reproduce the bug

1. 
![image](https://github.com/vuejs/pinia/assets/16078260/351ebce3-1692-407e-82b6-be9ad8f9962b)
2. 
![image](https://github.com/vuejs/pinia/assets/16078260/85934489-32f0-4178-a4cd-fa227f2d5772)
3. repeat step 1 and 2，the filterData data will lose reactive , always be [].

### Expected behavior

filterData  should always be reactive.

### Actual behavior

filterData at this demo  lose reactive, I should remove filterData out of useDataStore to make it work normal.

**Comment by posva** [comment]
This is because the reset function will, in your case break reactivity. It seems like you are trying to write a setup store or at least that it will fit better what you are trying to do. I would recommend you to transform the syntax by following the docs of setup stores and write your own reset function that sets the initial value of each state since setup stores do mot have a reset function. In option stores, the reset function just call the state function again and patches the current state. In your case the state function has side effects with the refs and the patch cannot be applied properly

**Comment by WormGirl** [comment]
Thanks, I will read docs carefully.

**Comment by WormGirl** [comment]
> This is because the reset function will, in your case break reactivity. It seems like you are trying to write a setup store or at least that it will fit better what you are trying to do. I would recommend you to transform the syntax by following the docs of setup stores and write your own reset function that sets the initial value of each state since setup stores do mot have a reset function. In option stores, the reset function just call the state function again and patches the current state. In your case the state function has side effects with the refs and the patch cannot be applied properly

I use composition setup store now, but the computed still lose reactive sometimes, I am very confused. i need to move all ref,computed,function out of defineStore to make this work normally.

**Comment by posva** [comment]
Make sure your reset function doesn’t create new refs or computed

**Comment by WormGirl** [comment]
> Make sure your reset function doesn’t create new refs or computed

sure, but  i don't know  why, I will reproduction this later.
