### ISSUE TITLE
Create a JavaScript version of the API documentation

### ISSUE THREAD

**Issue by thejspro** [posva/pinia#2272]
### What problem is this solving

The [official API documentation](https://pinia.vuejs.org/api/modules/pinia.html) is written for TypeScript users, and does not cater to JavaScript users.

For example, I was looking for a list of instance properties and methods, but instead I end up being bombarded with "Interfaces", "Type aliases" and other TypeScript-specific terminology. Without the intimate knowledge of TypeScript, I am unable to understand what methods and properties are available to me.

This is frustrating, because I need to migrate several Vuex modules and learning TypeScript right now, is not really an option.

The beauty of Vuex was it's simplicity - making TypeScript knowledge mandatory for Pinia users takes that away completely.

Please, comment respectfully - not everybody has switched to TypeScript yet and not everybody wants to.

### Proposed solution

Provide a simplified version of the API documentation for the JavaScript users, which would include a list of available properties and methods, without type annotations.

A great idea would be a toggle like on the official Vue website, where users can switch between Options and Composition API version of documentation.

**Comment by posva** [comment]
The API documentation is generated from the types but it's written for JS and TS users. While I understand the big list of interfaces can be frightening, one doesn't need to learn TS to travel through the docs. Moreover, it's simply impossible for me to write and maintain yet another version of the docs. My recommendation here is to spend some time in the docs to get used to navigating through the API documentation or to use the Guide which is for everybody. It will definitely take you less time to get comfortable with it than for someone to rewrite a new API documentation for JS users.

I definitely recommend you to start from the Guide rather than the API documentation to grasp what you need to migrate from Vuex. Then, taking a look at https://pinia.vuejs.org/cookbook/migration-vuex.html#migrating-from-vuex-%E2%89%A44

> The beauty of Vuex was it's simplicity

If there is anything you could say about Pinia compared to Vuex is that it is simpler 😄

> making TypeScript knowledge mandatory for Pinia users takes that away completely.

As shown in docs, TS is not a mandatory knowledge for Pinia. I'm confident that if you start from the getting started section docs, you will not only find the familiarity of state, actions, and getters from Vuex, but also realize how much less of a hassle pinia is compared to vuex.

**Comment by thejspro** [comment]
While I understand your reasoning and need to accept it, I have to say that I don't agree with it. However, many thanks for a quick reply and a thorough explanation.
