### ISSUE TITLE
watching asynchronous data can lead to inconsistent values in the store

### ISSUE THREAD

**Issue by baixiaoyu2997** [posva/pinia#2285]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-vibihh?file=pages%2Findex.vue,store%2Fwallet.ts

### Steps to reproduce the bug

check console log

### Expected behavior

`isSetOption` value should be `true`

### Actual behavior

`isSetOption` valuse is `false`

### Additional information

I want to modify the value of `isSetOption` to `true` in the `wallet store` by listening to the completion of asynchronous operations in the `chain store`. However, the final result is `false`, and there is no operation in my code to set `isSetOption.value` to `false`.

**Comment by baixiaoyu2997** [comment]
```ts
// wallet.ts
 watch(
    isReady,
    (newValue) => {
      if (newValue) {
        nextTick(() => {
          isSetOption.value = true;
        });
      }
    },
    {
      immediate: true,
    }
  );
```
use nextTick can fix this issue

**Comment by posva** [comment]
This is due to setting the state on the server in an async way without waiting for it to render:

- On server:
  - Application renders with the state set to false
  - state is sent to client
- On client:
  - For some reason, the promise resolves differently and changes the state **before returning the store**
  - After return the state is hydrated with the values from the server (false)

You have 2 problems here:

- The `isSetOption` is being set to false on server and to true on client due to the immediate watcher and Promises resolving with different timing
- The promise within useChainStore is not being awaited to render

In Nuxt, the easiest way to await for something is to do it within the script setup of a page:

- Add an action to the chain store
- await it in one of the components

But this won't be enough in your case because of the nature of watchers not being sync by default. On the server this will be necessary to trigger the update right away

[Here you have a fixed playground](https://stackblitz.com/edit/nuxt-starter-tub3pa?file=store%2Fwallet.ts)
