### ISSUE TITLE
Browser ESM build is broken

### ISSUE THREAD

**Issue by zigomir** [posva/pinia#28]
I'm trying to use ESM file directly from `unpkg.com`. The problem is that `pinia.esm.js` and `pinia.esm.min.js` both include `import { ref, watch, computed } from '@vue/composition-api';`.

Is this intentional? I'm actually trying it with freshly published [vue 3 build](https://unpkg.com/vue@3.0.0-alpha.0/dist/vue.esm.prod.js).

I see that `@vue/composition-api` is defined as global in rollup config. Maybe for vue 3 we'd need another build that doesn't rely on `@vue/composition-api`.

**Comment by posva** [comment]
This is intentional as the current version is for Vue 2. I didn't see any other way of handling the external dependency `@vue/composition-api`... I don't really know what is the best way to handle the external dependency in a browser module environment and wouldn't mind some advice/feedback

A vue 3 version should be easily buildable by replacing `@vue/composition-api` with `vue`. I think that having both versions available for the moment is feasible.

**Comment by posva** [comment]
@zigomir I published a new version for vue 3 under the tag `next`. Let me know what you think

**Comment by zigomir** [comment]
@posva great, thanks! Yeah, this works for me with minimal `rollup` setup/config.

Although, I had to [this change in vue-next](https://github.com/vuejs/vue-next/pull/553) in order to make it work.

I also don't know what is the best way to handle external dependencies with native ESM in browser, I'm only playing around.
