### ISSUE TITLE
Feature: Vue.js CLI Plugin for pinia

### ISSUE THREAD

**Issue by eladcandroid** [posva/pinia#42]

**Comment by posva** [comment]
Since Pinia is only a dependency that requires no changes to the project configuration or whatsoever, the only utility of the plugin would be to create a `stores` folder with an example store. I don't think I will do this yet as I prefer having an example to show to people of how things are meant to be organized with Pinia but I'm happy if someone wants to do this and add me as a collaborator

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/vue-cli-plugin-pinia

Does exactly what it needs to do for Vue 2/3 here https://pinia.esm.dev/getting-started.html and a simple counter store. Adds composition api plugin if missing in Vue 2
