### ISSUE TITLE
Patch does not update "deep" state

### ISSUE THREAD

**Issue by google-mac** [posva/pinia#43]
In my application, I return a user object when authenticated:

```json
{
    "id": 1,
    "username": "googlemac",
    "hasAccess": true,
    "roles": {
        "isAdmin": true,
    },
}
```

My issue is that updating the user state with `store.patch()` does not have the desired effect for "deep" data. All of the data is correctly updated (shown in devtools) and the username (regular state) in the UI is updated, but trying to reference `state.roles.isAdmin` is not reactive. The getter is also not reactive. If I instead update the state directly, accessing the state directly or through the getter works properly.

I have defined my store:

```ts
function state() {
    return {
        employeeId: 0,
        username: '',
        hasAccess: false,
        roles: {},
    } as User;
}

export type RootState = ReturnType<typeof state>;

const getters = {
    isRestricted: (state: RootState) => !state.hasAccess,
    isAdmin: (state: RootState) => state.roles?.isAdmin ?? false,
};

export const fetchUser = async () => {
    const store = useUserStore();

    const { data } = await axios.get('/api/user');
    const { user } = data;

    // NOTE: this does not work!
    // store.patch(user);

    // NOTE: this works as desired
    store.state.employeeId = user.employeeId;
    store.state.username = user.username;
    store.state.hasAccess = user.hasAccess;
    store.state.roles = user.roles;
};
```

Also, is there a way to make the getter `state` already typed with the root state? It's only one line and not that big of a deal, but it may help. If I don't put this, I get a TS error that it is `any` type.

**Comment by posva** [comment]
Regarding the data not being reactive, it happens because patch only sets a value, it suffers from the same reactivity caveats as Vue 2. Is there a reason not to initialise the `roles.isAdmin` property?

To get the typing automatically work, don't split in different objects, use `createStore` like in the readme and `state` will automatically be connected by the typing

**Comment by google-mac** [comment]
The roles object will be unknown at runtime. It's a bag of different roles the user may have. Perhaps this is a good thing to point out to users. Or is there a way to run through the object and actually trigger a re-render?

For the second part, that makes sense. I do like splitting them up so it doesn't get unbearable, so I'll keep it this way. Thank you though!

**Comment by posva** [comment]
The reactivity problem is worth being reminded in the readme, yes

**Comment by google-mac** [comment]
For anyone else reading this issue, the preferred solution is to define the nested state beforehand. Then the updates are reactive. If this cannot be done, such as in my case above, you must set the state property directly, effectively replacing the state value (as is done often in Vue 2).

**Comment by theolavaux** [comment]
Has this been documented somewhere ? I also ran into the problem with `patch` not triggering reactivity updates for deep state

**Comment by awacode21** [comment]
@parker-codes Can you give a code sample?

**Comment by posva** [comment]
You can use Vue 2's `Vue.set()` onto `store.$state` or `pinia.state.value[store.$id]` (they refer to [the same object](https://pinia.vuejs.org/core-concepts/state.html#replacing-the-state) to **add non-existing** state properties. Note these **won't be proxied to the store (`store.newProperty`)** unless you [set it yourself like in plugins](https://pinia.vuejs.org/core-concepts/plugins.html#adding-new-state)

**Comment by awacode21** [comment]
thank you

**Comment by tiagoroldao** [comment]
@posva before I create a new ticket, I thought I'd ask: does it not make sense to make `$patch` reactive-ready? As in, use `vue-demi`'s `set` to ensure compatibility with Vue2 usage.

I ask because there are use-cases where dynamic properties are necessary/useful and where bypassing $patch is not trivial, such as when using a plugin. An example is [pinia-plugin-persistedstate](https://prazdevs.github.io/pinia-plugin-persistedstate/) - it uses $patch to hydrate the store using localstorage data, and thus setting new keys if a dynamic approach is being used.
