### ISSUE TITLE
Data changed unexpectable after change the route

### ISSUE THREAD

**Issue by ParkerFiend** [posva/pinia#510]
In the development process, I got a problem in using pinia.
I wonder if I'm using it in the wrong way, please give me a hint.

### Reproduction
https://codesandbox.io/s/oqlps

### Steps to reproduce the behavior

1. Go to Path '/bar', count as expected.
2. Click on 'goto Foo'.
3. countdown value stoped.

### Expected behavior

As expected, countdown go correctly in another route.

Thanks.

**Comment by philippedasilva-orizone** [comment]
I'm no expert on Vue but here is what I'm guessing is happening:
You call `useStore()` on both components but the actual lifespan of the store and its actions is on a per component basis: as soon as you switch from one component to another, your actions aren't running anymore since the previous `useStore()` returned instance is killed when the component gets unmounted.
You are then creating a NEW instance of the store in the `Foo` component which does know nothing of previous calls to actions.

If you want this to work, you can either:

1. create your store instance and call its actions at the `App` level (parent to the components you currently are using)
2. or add another `onMounted()` call in your Foo component that will call the `startCounter()` method too.

**Comment by ParkerFiend** [comment]
@philippedasilva-orizone
I got your point, thanks！
In the actual development, I solved it by using the first solution.

And I tried the second solution in the codesandbox, the countdown just beat(not decrease).

By the way, dose this mean that using timer in the component store is not a good idea?

**Comment by posva** [comment]
The problem comes from the `setInterval` being called after Bar is unmounted. Due to a limitation of the current implementation (https://pinia.esm.dev/core-concepts/plugins.html#introduction) the access to `this.anyState` isn't tracked. This could be solved for state properties until the RFC is merged and released but cannot be patched for getters.

You can however access the state properties through `$state` which is a plain getter on the root pinia:

```js
import { defineStore } from "pinia";

export const useStore = defineStore({
  id: "app",
  state: () => ({
    timer: null,
    countdown: 60
  }),
  actions: {
    startCount() {
      if (this.timer) return
      this.timer = setInterval(() => {
        if (this.$state.countdown <= 60) {
          this.$state.countdown--;
          console.log(this.$state.countdown);
        }
      }, 1000);
    }
  }
});
```

Using the store at `App` is an easier workaround though. You don't even need to touch it:

```js
// In App.vue
setup() {
  useMyStore()
}
```
