### ISSUE TITLE
[Question] Usage outside of Vue component

### ISSUE THREAD

**Issue by rijkvanzanten** [posva/pinia#65]
Heya! I've been playing around with Pinia lately, and am really in love with it so far. I do have one question though, the docs state very clearly that you can only call the store compositions from inside the deferred `setup` function of Vue components:

> There is one important rule for this to work: the useMainStore (or any other useStore function) must be called inside of deferred functions. This is to allow the Vue Composition API plugin to be installed. Never, ever call useStore like this:

```js
import { useMainStore } from '@/stores/main'
// ❌ Depending on where you do this it will fail
// so just don't do it
const main = useMainStore()

export default defineComponent({
  setup() {
    return {}
  },
})
```

However, does that mean that it's completely impossible to read the store from other files? For example, my use case would be to read a value from the store in a navigation guard in my Vue Router `router.js` file.

In the tests, you seem to use the store without mocking the `setup` function, but I might be mistaken:

https://github.com/posva/pinia/blob/master/__tests__/actions.spec.ts#L52

**Comment by posva** [comment]
I'm glad you are liking it!

It doesn't have to be used inside a `setup` function. It has to happen after the Vue Composition API plugin is installed, otherwise it will fail. Calling `useStore` inside a guard is fine.
This problem goes away with Vue 3, I do have to make the `next` branch a bit more visible and update its readme.

That's why the `useStore` should be inside functions, to defer its retrieval. When dealing with SSR, it's a bit more tricky because you have to ensure the correct store is retrieved for the given request, so you have to pass the `req` object to `useStore`. If you are not dealing with SSR, this last part doesn't concern you.

I will update the docs to bring more clarity around this by adding an extra example without a `setup` function.
