### ISSUE TITLE
Allow to exclude properties from the store.$reset() method

### ISSUE THREAD

**Issue by DannyFeliz** [posva/pinia#746]
### What problem is this solving

Sometimes we have modals or wizards and we need to reset the state of a store entirely except for 1 or 2 properties.

### Proposed solution

It would be cool if the [store.$reset()](https://pinia.esm.dev/core-concepts/state.html#resetting-the-state) could accept an object with the property `exclude` which will ignore the reset action, the API would be something like this:

```js
store.$reset({
  exclude: [
    "curren-step",
    "user.company.name" // nested property
  ]
})
```

### Describe alternatives you've considered

I know I could move the state out of the store I want to reset, but I think It would be cool to have that.

**Comment by posva** [comment]
The reset functionality is intentionally very limited. It only calls the `state()` function to replace the whole state. IMO I would even move it to a plugin since the setup syntax doesn't support `$reset()` at all (unless you implement it yourself).

This kind of behavior can be added through a plugin or also with an action.
